git checkout --orphan $1
ls -a | grep -v .git | xargs rm -r
cat > README.md <<EOF
# Storage branch

> Branch used to store statics files generated by GitHub actions, like coverage reports, badges, etc...
> Resulting files can then be used in README documentation, issues, or anywhere else.
EOF
git add README.md && git commit -m "Create storage branch" && git push
