# Extract project name from remote url
github_project=$(git remote get-url origin | sed 's/https:\/\/[a-zA-Z\.]*\/\([a-zA-Z0-9\.\/\-]*\)\.git/\1/g')

# Create a new orphan branch unrelated history
git checkout --orphan $1

# Remove all files on orphan branch (except .git/ folder)
ls -A -I .git | xargs rm -r

# Add a default message to document the purpose of this branch
cat > README.md <<EOF
# Storage branch

> Branch used to store statics files generated by GitHub actions, like coverage reports, badges, etc...
> Resulting files can then be used in README documentation, issues, or anywhere else.
EOF

# Create initial commit and push the new branch to remote
git add README.md && git commit -m "Create storage branch" && git push -u origin $1
